FROM python:3.12-slim

WORKDIR /app

COPY cloud-redteam/api-server/requirements.txt .
RUN pip install \
    --no-cache-dir \
    --timeout 120 \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    -r requirements.txt

COPY cloud-redteam/api-server .

CMD ["python", "main.py"]
